# Generated by Django 4.2.11 on 2024-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0006_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('CL', 'Cancelled'), ('P', 'Pending'), ('CP', 'Completed')], default='P', max_length=2),
        ),
    ]
