# Generated by Django 4.2.11 on 2024-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0008_purchaseorder_response_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='response_time',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('CP', 'Completed'), ('CL', 'Cancelled'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
