# Generated by Django 4.2.11 on 2024-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0009_remove_purchaseorder_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('CL', 'Cancelled'), ('CP', 'Completed'), ('P', 'Pending')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.DurationField(null=True),
        ),
    ]
