# Generated by Django 4.2.11 on 2024-05-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0010_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('CP', 'Completed'), ('CL', 'Cancelled')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='vendorperformancehistory',
            name='average_response_time',
            field=models.DurationField(null=True),
        ),
    ]
